### ISSUE TITLE
Color enhancement

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#15]
Gomb szín javaslatok (a Kubuntu 19.04 témájából):
        ◦ háttér: 54, 57, 60
        ◦ gomb: 28, 33, 38
        ◦ gomb kerete simán: 108, 110, 114
        ◦ a gomb felirata fehér színű, vagy lényegében fehér
        ◦ a gomb aktívan kék keretes lesz: 114, 193, 233
        ◦ a gomb háttérszíne (és kerete) kattintás közben: 61, 174, 230

**Comment by Btimes2** [comment]
Apple color palette: https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/ 

Ez alapján az interakció gombok (yes, no, on, off) színe ilyen lehetne:
        ◦ zöld háttérszín: 44, 69, 39
        ◦ zöld vonalszín + betűszín: 99, 213, 56
        ◦ piros háttérszín: 76, 37, 45
        ◦ piros vonalszín + betűszín: 230, 46, 120
        ◦ ha pedig aktívak, akkor kaphatnának sárga vagy fehér keretet, úgy, mint most is

**Comment by Btimes2** [comment]
Most kicsit  úgy érződik, mintha ki lehetne jelölni a highscores bejegyzéseket. Szerintem eltűnne ez az érzés, ha a gomb nem kapna keretet (vagy a keretszín azonos lenne a gomb hátterével).

**Comment by Btimes2** [comment]
A Highscores gomb neve elavult (nincsenek már pontok), lehetne mondjuk Records, vagy Personal best. És elé meg utána tehetnél egy szóközt, hogy ránézésre nagyobb margója legyen a gombnak.

**Comment by Sasszem** [comment]
PRs are welcome
You should check:
- `src/menu/buttonStyle.lua` for global button styling
- `src/menu/OptionsMenu.lua` for yes/no buttons
- `src/menu/MainMenu.lua` for replacing the text of the "Highscores" button
(although a bigger refactor also should follow that)
