### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#16]
A számoknál picit fura nekem a 8-as, ami úgy néz ki, mint egy kis lakat.
Szerintem ezekkel a fontokkal is jól nézne ki a játék:
Kalam - ez egy kézírásra emlékeztető font, nagyon szépek a számjegyek:
https://www.1001fonts.com/search.html?search=kalam&text=0123456789
Oregano - ez is kézírást imitál, de picit szabályosabb, hagyományosabb a számok írása:
https://www.1001fonts.com/search.html?search=oregano&text=0123456789

Mindkettő letölthető legálisan, és mindkettő ismeri a magyar ékezeteket is.

**Comment by Sasszem** [comment]
I've listed all mentions of the current font:
- src/Config.lua
- src/menu/OptionsMenu.lua
- src/menu/HighscresMenu.lua
- src/menu/MainMenu.lua
- src/menu/menu.lua
- CREDITS.md

<del>Fork this project, create a feature branch, implement the changes and make a PR!</del>
Just clone the repo, create a feature branch and implement on that. Push and PR when you are done.
