### ISSUE TITLE
Indítások

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#17]
- Amikor már nyertem, akkor ne kezdjen új számokat hozzáadni, meg azokat meganimálni. Most úgy van, hogy már szól a nyertes zene, de még nem írja ki, hogy nyertem.
- Timed módban ne induljon addig a számláló, amíg rá nem bökök a képernyőre.

**Comment by Sasszem** [comment]
So...
Trigger game end immediately after merging the cell would work?
Second one is a bit harder, but I'm thinking on it.

**Comment by Btimes2** [comment]
Yes, the end music should wait until the animation ends.

**Comment by Sasszem** [comment]
> Yes, the end music should wait until the animation ends.

Easy then. End music is started on merging in the task in `src/Path.lua`. Just move that start to the end of `src/tasks/growCells.lua`
