### ISSUE TITLE
Nagyobb átalakítást igénylő eye-candy ötletek

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#18]
- A számok lehetnének egy pici ívben lekerekítettek?
- Amikor elkezdek összehúzni számjegyeket, akkor ne piros legyen a vonal, hanem fehér - az feltűnőbb, illetve azért jó, mert az 1-es is fehér.
- Path rajzolás közben kaphatnának a kijelölt számjegyek és a path maga is egy fehéres glow effektet, szerintem az nagyon interaktívan nézne ki. Illetve amikor a számok animálásra kerülnek, akkor füstként utánuk gomolyoghatna ez a glow.

**Comment by Sasszem** [comment]
Split up into #23 #24 #25
