### ISSUE TITLE
Nemzetközi támogatás

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#19]
Csinálhatnál belőle magyar verziót is, főleg anya kedvéért :) 
Igazán hasznos persze az lenne, ha minden szöveget egy .po fájlból venne a program, és az opciók menüben egy mozdulattal lehetne váltani a különböző .po fájlok között. Az angol, német és francia fordítást simán meg tudjuk csinálni mi is, mások meg bővíthetnék tovább, ha akarják.

**Comment by Sasszem** [comment]
Sounds like a cool idea, and also not that hard to implement. 
I would not think in .po files, but rather in .lua files containing tables. It's a simple game, so we do not even have to worry about singular / plural forms, just name->string translations for a dozen or less strings.
The only difficulty should be dynamic reloading, e.g changing them when you change the setting.

**Comment by Btimes2** [comment]
Dynamic reloading is not really needed, lots of apps only show a label: "needs restart"

**Comment by Sasszem** [comment]
Lazy-ass solution, might use it...
