### ISSUE TITLE
About menü

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#21]
Mindenképpen jó lenne egy About menü, főleg a licenszek miatt (zene, font), de azért is, mert akkor szerepelhetne benne a verziószám is. Meg a kiadás dátuma.

**Comment by Sasszem** [comment]
Easy:
- create a new file like "AboutMenu.lua" in `src/menu/`
- implement UI fragment - I recommend a `VDiv` with simple labels inside
- add a back button to it
- register new UI fragment in `src/menu/menu.lua`
- add link button to it in `src/menu/MainMenu.lua`
