### ISSUE TITLE
Ikon

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#22]
Csináltam egy ikont 3 szín variánssal. Csatoltam:
[Freepik.zip](https://github.com/Sasszem/13/files/4806930/Freepik.zip)

Ezek legálisan használhatók, de ki kell írni az About menübe:
"13 icon was designed by Freepik from Flaticon."
És ha valaha bekerül a Google Play-be az app, akkor ott az app description-jében is ki kell írni ugyanezt a szöveget.

Bővebben:
https://support.flaticon.com/hc/en-us/articles/207248209-How-I-must-insert-the-attribution-

**Comment by Sasszem** [comment]
For the APK, we need to render it in many different sizes too. Will do it for a new release.
