### ISSUE TITLE
Starting sound

### ISSUE THREAD

**Issue by Btimes2** [Sasszem/13#44]
The app starts with a distorted click sound, that should be fixed.

**Comment by Btimes2** [comment]
Or not click, but it is short. It is only noticeable if music is turned off.

**Comment by Sasszem** [comment]
<del>Just flip options load and sound start in `main.lua`!</del>

**Comment by Btimes2** [comment]
I flipped everything remotely resembling option load and sound, it is still noticeable.

**Comment by Sasszem** [comment]
Mute sounds and music before loading the optios in the same file!
